version: '3'
services:
  esrs-api:
    ports:
      - "5000:5000"
    image:
      willnx/vlab-esrs-api
    environment:
      - VLAB_URL=https://localhost
      - INF_VCENTER_SERVER=virtlab.igs.corp
      - INF_VCENTER_USER=Administrator@vsphere.local
      - INF_VCENTER_PASSWORD=1.Password
    volumes:
      - ./vlab_esrs_api:/usr/lib/python3.8/site-packages/vlab_esrs_api
    command: ["python3", "app.py"]

  esrs-worker:
    image:
      willnx/vlab-esrs-worker
    volumes:
      - ./vlab_esrs_api:/usr/lib/python3.8/site-packages/vlab_esrs_api
      - /mnt/raid/images/esrs:/images:ro
    environment:
      - INF_VCENTER_SERVER=changeME
      - INF_VCENTER_USER=changeME
      - INF_VCENTER_PASSWORD=changeME
      - INF_VCENTER_TOP_LVL_DIR=/vlab

  esrs-broker:
    image:
      rabbitmq:3.7-alpine
